project_id = "uenonnpdwipdwbdbxlma"

[functions.send-booking-notification]
verify_jwt = false

[functions.create-staff-user]
verify_jwt = true

[functions.setup-first-admin]
verify_jwt = false

[functions.delete-staff-user]
verify_jwt = true

[functions.reschedule-booking]
verify_jwt = true

[functions.send-patient-email]
verify_jwt = true